trailingComma: 'es5'
tabWidth: 4
semi: false
singleQuote: true
jsxSingleQuote: true
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: 'always'
htmlWhitespaceSensitivity: 'css'
endOfLine: 'lf'
embeddedLanguageFormatting: 'auto'
